module.exports = {
  INITIAL_STATE: 'INITIAL_STATE',

  RESOLVED   : 'RESOLVED',
  NONEXISTENT: 'NONEXISTENT',

  CREATING: 'CREATING',
  UPDATING: 'UPDATING',
  DELETING: 'DELETING',
  FETCHING: 'FETCHING',

  ERROR_CREATING: 'ERROR_CREATING',
  ERROR_UPDATING: 'ERROR_UPDATING',
  ERROR_DELETING: 'ERROR_DELETING',
  ERROR_FETCHING: 'ERROR_FETCHING'
};
